services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PromotionEngineBundle\Command\:
    resource: '../../Command/'
  PromotionEngineBundle\Controller\:
    resource: '../../Controller/'
  PromotionEngineBundle\Repository\:
    resource: '../../Repository/'
  PromotionEngineBundle\Service\:
    resource: '../../Service/'
    public: true
  PromotionEngineBundle\Procedure\:
    resource: '../../Procedure/'
